#jasypt:
#  encryptor:
#    password: Datarse_PAmaster
#    bean: jasyptStringEncryptor


spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/api_db?serverTimezone=Asia/Seoul&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true
    username: test03
    password: 1q2w3e4r5t
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update    # 개발용 only
    properties:
      hibernate:
        show-sql: true
        format-sql: true

jwt:
  secret: jwtsecret        

server:
  port: 9000

front:
  host:
    url: http://localhost:5000

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: DEBUG