#jasypt:
#  encryptor:
#    password: Datarse_PAmaster
#    bean: jasyptStringEncryptor

jwt:
  secret: jwtsecret        

server:
  port: 9000

front:
  host:
    url: http://localhost:5000

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: DEBUG
        com.zaxxer.hikari.pool.PoolBase: ERROR
        com.zaxxer.hikari.pool.HikariPool: ERROR
        com.zaxxer.hikari.HikariDataSource: ERROR

